### ISSUE TITLE
PortMaster doesn't work on rg34xx sp

### ISSUE THREAD

**Issue by ztx-lyghters** [cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification#206]
At first I tried to download runtimes, but it crashed three times exactly on the last one (every time there was one less to download, however the last one was always java 8). I got tired of trying and decided to say no to downloading. PortMaster logo/animation appears for a second, but then everything glitches out and just some artifacts are left on screen. The only way to get out of this state is by resetting or powering off. This is a fresh installation. (I chose the third release from the top, IIRC, the latest one with the image for rg34xx sp)

![Image](https://github.com/user-attachments/assets/2ac882c7-eebb-4a6f-94e5-78500edbec15)

**Comment by cbepx-me** [comment]
It may be caused by the stability of the network connection. You can try to update offline
https://github.com/cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification/releases/tag/20250930

**Comment by cbepx-me** [comment]
Thank you for your feedback. The issue has been resolved

**Comment by ztx-lyghters** [comment]
Thank you for the quick response. I have downloaded the new version of app.py from repository and replaced the one at `/root/mnt/mmc/Roms/APPS/port_master/` (via SMB), but I still have all the above issues. Do I maybe have to do something else on my end?

**Comment by cbepx-me** [comment]
Please copy this file to the Roms/APPS folder of TF1 or TF2, and run it once in the apps of the app center.

[fix_portmaster.sh](https://github.com/user-attachments/files/22706669/fix_portmaster.sh)

**Comment by cbepx-me** [comment]
> Also, I just noticed, do you not need to do the same changes that you've made at line 280 of the app.py in the block at line 270?

Another similar code block does not need to be modified.

**Comment by ztx-lyghters** [comment]
> Please copy this file to the Roms/APPS folder of TF1 or TF2, and run it once in the apps of the app center.
> 
> [fix_portmaster.sh](https://github.com/user-attachments/files/22706669/fix_portmaster.sh)

I executed the script, and the glitches/system freezing are gone, but now the program just closes after the logo

**Comment by ztx-lyghters** [comment]
https://github.com/user-attachments/assets/8c2b6780-50c7-4dd0-b18e-b94647b70670

**Comment by ztx-lyghters** [comment]
Ok, so first of all, I'm not sure how can I be using the stock OS if I downloaded this project's image (compatible woth rg34) from releases and flashed it to my SD card with dd, completely erasing whatever was in there before. It ran installer during the first boot.

Secondly, the stock OS had all space on the SD card allocated. However, the modded version left 45GB unallocated at the end (my SD card for the left slot is 64GB). Checking for free space won't solve the problem of rootfs having 0 bytes free after installing all the PortMaster runtimes (it asks and lets you install runtimes before launching the PortMaster itself, so I was able to download them despite PortMaster itself crashing), that was enough to run out of the free space. 

Original stock OS had one of the partitions separate from rootfs, /mnt/mmc if I remember correctly (the one called "sd1" on SMB), but in modded version it is a part of rootfs partition and shares the same space with it (7GB). Maybe there's an error in the initial OS installation script and it actually supposed to make it separate? In any case, I'd propose detrcting SD card size and just allocating the rest of the free space to rootfs (partition 5) during the first boot installation.

Also, since I already allocated the free space to rootfs manually with GParted, I now have 45GB free, so whatever is preventing the update from happening must not be a free space related problem. I'll download the offline update version after work and try to log the script's output to look for errors.

**Comment by ztx-lyghters** [comment]
Did you perhaps mean that this problem is out of scope of the modded OS? I don't know if the system installer is your own or is from the stock OS and you just add new apps on top of the stock system. I don't know how you're building the images before publishing them in releases, nor was I able to find the installer script, which runs once during the first boot. Can I view it somewhere? I might be able to make some changes to utilize the space which doesn't get allocated. At least I would like to give it a try and experiment.

**Comment by ztx-lyghters** [comment]
> it is due to the idle limit of the/dev/mmcblk0p5 partition

yes, this is true, but the problems is that /mnt/mmc is a part of /dev/mmcblk0p5. I'm going to open a separate issue in this, this is not relevant to PortMaster crashing

**Comment by cbepx-me** [comment]
/dev/mmcblk0p8 is unique to the Stock OS mod, but not to Stock OS

**Comment by ztx-lyghters** [comment]
I just re-flashed my SD card on my laptop using the "RG34XXSP-V1.0.2-BASE-20250523-MOD-v3.7.0.img.7z" image from Google Drive. Prior to that I manually removed all partitions with cfdisk, just in case, then used the dd command to flash the image:
`dd if="/path/to/RG34XXSP-V1.0.2-BASE-20250523-MOD-v3.7.0.img.7z" of=/dev/mmcblk0`

This is the result, seven partitions and 45.9GB of free, unallocated space:
![Image](https://github.com/user-attachments/assets/9bc03b0d-5bfd-4fe7-8487-43d5c858b636)

After that I inserted the sd card into my rg34xx sp and started the installation process. After the installation, I opened simple terminal in tools and ran `cfdisk /dev/mmcblk0`. It's still the same seven partitions, there is no mmcblk0p8:
![Image](https://github.com/user-attachments/assets/42254d58-d5f7-46b7-8dae-b4c6b7f0f9e1)

**Comment by ztx-lyghters** [comment]
System update still doesn't apply correctly, after update the updater still thinks the system is 3.7.0 and prompts for updating to 3.7.1, indefinitely.
PortMaster, upon the first launch, told me there is an update available and asked I wanted to update. I chose "yes". After it updated I decided not to download the runtimes. After that PortMaster glitches out like in my initial post in this issue. Maybe I shouldn't have updated it?

**Comment by cbepx-me** [comment]
DD has limited support for GPT partitioning. Please use Rufus to swipe the card on Windows, or refer to: https://github.com/cbepx-me/Anbernic-H700-RG-xx-StockOS-Modification/issues/68

**Comment by DearFox** [comment]
~~Are the fix_portmaster.sh and fix_portmaster2.sh scripts out of date? I couldn't find them in the latest firmware version even after updating to v3.8.2~~

After updating the firmware to v3.8.2, the PortMaster app started working!

The only problem is that it uses Chinese by default, and if you don't know where to click to change the language, it can be a bit tricky.

<details>
  <summary>How to change the language in the PortMaster app</summary>
  
  
<img width="1147" height="771" alt="Image" src="https://github.com/user-attachments/assets/a2a2baf8-7b12-4b82-8d4d-8b7983d8ef9b" />

<img width="1159" height="786" alt="Image" src="https://github.com/user-attachments/assets/355d16d4-31fc-4112-9b66-3a3a5129dd69" />

  
</details>

I hope other RG34xxsp owners will confirm that the problem has been resolved after updating the firmware to this version.
